#!/bin/bash
###########################################################
# Script de configuracion de la plantilla de las diferentes distros WSL
# Requiere common.inc en el mismo directorio
#
###########################################################

trap "exit 1" TERM
export PIDP=$$

BASE=${0%%/*}

source ${BASE}/common.inc
source ${BASE}/wsl_base_dialog.inc

test `id -u` -gt 0 && noroot

log_file $0

apt-get update &>> $LOG
apt-get install -y dialog &>> $LOG

get_config            # Interfaz para informacion de usuario

info Iniciando configuracion

info Descargando paquetes basicos
. ${BASE}/wsl_base_packages.sh

ln -s /mnt/c/${ROOT}/shared             /mnt/s
ln -s /mnt/c/${ROOT}/${WSL_DISTRO_NAME} /mnt/m

info Configurando usuarios

MYSELF=`ls -l /home | cut -f10 -d' '`
cat /mnt/s/wsl_tools/dat/profile.conf >> /home/${MYSELF}/.profile

if [ $SET_GROUP -gt 0 ] ; then
    groupadd $GROUP -g 3000
fi    

if [ $SET_USER -gt 0 ] ; then
    useradd -u 2000 -p $PWD -G $GROUP -d /home/$USER $USER
    copy /home/${MYSELF}/.* /home/${USER}
    chown ${USER}:${USER} /home/${USER}/.*
fi    

info Configurando WSL y red
cp -f /mnt/s/wsl_tools/dat/wsl.conf    /etc/wsl.conf
sed -i 's/HOSTNAME/$WSL_DISTRO_NAME/g' /etc/wsl.conf
sed -i 's/USER/$MYSELF/g'              /etc/wsl.conf

grep -q $WSL_DISTRO_NAME /etc/hosts
if [ $? -ne 0 ] ; then
    echo "127.0.0.1      $WSL_DISTRO_NAME"  >> /etc/hosts
    
    
 

# #!/bin/bash
# #
# 
# echo Ejecutando el fichero de configuracion de Base
# source /mnt/s/bin/common.inc
# 
# . wsl_default_packages.sh
# 
# exit 0
# 
# 
# 
# 
# 
# test -f /etc/${WSL_DISTRO_NAME].conf && already_run $0
# 
# 
# if [ `id -u` != 0 ] ; then
#    echo Este script se debe ejecutar como root
#    exit -1
# fi   
# 
# HEADER='Configuracion de distro'
# INPUT=
# USER=juan
# 
