REM Variables de configuracion para WSL
REM ATENCION A LA DIFERENCIA ENTRE WSL_MACHINES_WIN Y WSL_MACHINES_WSL

SET WSL_MACHINES_DRIVE=M:
SET WSL_MACHINES_WIN=C:\Maquinas
SET WSL_MACHINES_WSL=C:/Maquinas
SET WSL_USER=kvothe
SET WSL_PWD=kvothe
SET WSL_GROUP=temerant
